services:
  Facturador.Repositories.UsuarioRepository:
    class: ../../../contexts/facturador/usuarios/infrastructure/repositories/TypeORMUsuarioRepository
    arguments: []

  Facturador.Services.AuthenticationService:
    class: ../../../contexts/facturador/usuarios/infrastructure/services/JWTAuthenticationService
    arguments: ['@Facturador.Repositories.UsuarioRepository']

  Facturador.Usuarios.UseCases.LoginUseCase:
    class: ../../../contexts/facturador/usuarios/application/useCases/LoginUseCase
    arguments: ['@Facturador.Services.AuthenticationService']
  
  Facturador.Usuarios.UseCases.CheckIsAuthenticatedUseCase:
    class: ../../../contexts/facturador/usuarios/application/useCases/CheckIsAuthenticatedUseCase
    arguments: ['@Facturador.Services.AuthenticationService']
  
  Facturador.Usuarios.Controllers.LoginController:
    class: ../../../contexts/facturador/usuarios/infrastructure/controllers/LoginController
    arguments: ['@Facturador.Usuarios.UseCases.LoginUseCase']
  

  
    