services:
  Administrador.Repositories.UsuarioRepository:
    class: ../../../contexts/administrador/usuarios/infrastructure/repositories/TypeORMUsuarioRepository
    arguments: []

  Administrador.Services.AuthenticationService:
    class: ../../../contexts/administrador/usuarios/infrastructure/services/JWTAuthenticationService
    arguments: ['@Administrador.Repositories.UsuarioRepository']

  Administrador.Usuarios.UseCases.LoginUseCase:
    class: ../../../contexts/administrador/usuarios/application/useCases/LoginUseCase
    arguments: ['@Administrador.Services.AuthenticationService']

  Administrador.Usuarios.UseCases.CheckIsAuthenticatedUseCase:
    class: ../../../contexts/administrador/usuarios/application/useCases/CheckIsAuthenticatedUseCase
    arguments: ['@Administrador.Services.AuthenticationService']

  Administrador.Usuarios.Controllers.LoginController:
    class: ../../../contexts/administrador/usuarios/infrastructure/controllers/LoginController
    arguments: ['@Administrador.Usuarios.UseCases.LoginUseCase']
